const { chromium } = require('playwright');
const path = require('path');
const assert = require('node:assert/strict');
(async()=>{
  const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL || 'chrome'});
  const page=await browser.newPage({viewport:{width:1440,height:1080},deviceScaleFactor:1});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:8765');
  await page.getByRole('heading',{name:'Heizungsraum · AL1350 (Demo)'}).waitFor();
  assert.equal(await page.locator('[data-port]').count(),4);
  assert.equal(await page.locator('[data-value="1:flow"]').first().textContent(),'4,424 m³/h');
  await page.screenshot({path:'tmp/overview-desktop.png',fullPage:true});
  await page.locator('#master').selectOption('demo8');
  assert.equal(await page.locator('[data-port]').count(),8);
  await page.screenshot({path:'tmp/overview-8ports.png',fullPage:true});
  await page.locator('#master').selectOption('demo4');
  await page.locator('[data-port="2"]').click();
  await page.getByLabel('Gerätebezeichnung',{exact:true}).fill('Poolfilter Test');
  await page.getByLabel('Standort',{exact:true}).fill('Technikraum');
  await page.getByRole('button',{name:'Portzuweisung speichern'}).click();
  await page.getByText('Portzuweisung gespeichert.',{exact:false}).waitFor();
  await page.waitForTimeout(2200);
  assert.equal(await page.getByLabel('Standort',{exact:true}).inputValue(),'Technikraum');
  await page.getByRole('button',{name:/Gerätebibliothek/}).click();
  const filename=process.argv[2] || path.join(process.cwd(),'tests/fixtures/pn7096_status_b.xml');
  await page.locator('#iodd-upload').setInputFiles(filename);
  await page.locator('#variant').waitFor();
  assert.equal(await page.locator('#variant option').count(),2);
  await page.locator('#test-raw').fill('4E5C0100');
  await page.getByRole('button',{name:'Übersetzung testen'}).click();
  await page.waitForFunction(()=>document.querySelector('ifm-iolink-panel').shadowRoot.querySelector('#test-output').textContent.includes('2.006'));
  await page.screenshot({path:'tmp/library-import.png',fullPage:true});
  await page.getByRole('button',{name:'Geräteprofil speichern'}).click();
  await page.getByText('Geräteprofil gespeichert.',{exact:false}).waitFor();
  await page.getByRole('button',{name:'Portübersicht',exact:true}).click();
  const profileId=await page.locator('#assignment select option').filter({hasText:/^PN7096/}).first().getAttribute('value');
  assert(profileId.startsWith('custom_'));
  await page.locator('#assignment select').selectOption(profileId);
  await page.getByRole('button',{name:'Portzuweisung speichern'}).click();
  await page.waitForTimeout(1800);
  await page.locator('[data-port="4"]').click();
  await page.locator('#assignment select').selectOption(profileId);
  await page.getByRole('button',{name:'Portzuweisung speichern'}).click();
  await page.waitForTimeout(1800);
  await page.locator('[data-port="3"]').click();
  const download=page.waitForEvent('download');
  await page.getByRole('button',{name:'Portzuweisung speichern'}).click();
  assert((await download).suggestedFilename().includes('debug'));
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'tmp/overview-mobile.png',fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  assert.deepEqual(errors,[]);
  console.log('PASS: 4/8 ports, live rendering, assignment, IODD variant import, decoding, profile reuse, unknown debug, mobile width; no page errors.');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
